import re

input_file = "../recepty_ingredience.txt"
output_file = "recepty_ingredience_ocistene.txt"

ocistene_ingredience = [
    "acai",
    "agar",
    "ajvar",
    "alobal",
    "amaretto",
    "ananas",
    "angrešt",
    "anýz",
    "ančovičky",
    "aperol",
    "apetito",
    "arašídy",
    "artyčoky",
    "avokádo",
    "badyán",
    "bageta",
    "baileys",
    "baklažán",
    "balkánský sýr",
    "balzamikový ocet",
    "bambusové výhonky",
    "banány",
    "batáty",
    "bazalka",
    "becherovka",
    "bešamel",
    "bobkový list",
    "borůvky",
    "bouquet garni",
    "brambory",
    "brandy",
    "brokolice",
    "broskve",
    "brusinky",
    "bryndza",
    "buchty",
    "bulgur",
    "bulky",
    "burizony",
    "burrata",
    "buřty",
    "bylinky",
    "bílek",
    "bůček",
    "calvados",
    "camembert",
    "candát",
    "celer",
    "celozrnná mouka",
    "cherry rajčata",
    "cherry rajčátka",
    "chia semínka",
    "chilli",
    "chleba",
    "chlebové střídky",
    "chléb",
    "chobotnice",
    "chorizo",
    "chutney",
    "chřest",
    "ciabatta",
    "cibule",
    "cibulka",
    "cibulky",
    "cihla",
    "citron",
    "citronová tráva",
    "cizrna",
    "cornflakes",
    "cukerin",
    "cuketa",
    "cukr",
    "cukroví",
    "deko",
    "dort",
    "dressing",
    "drobenka",
    "droždí kostky",
    "drůbky",
    "dýně",
    "dýňová semínka",
    "džem",
    "džus",
    "eidam",
    "ementál",
    "estragon",
    "fazole",
    "fazolky",
    "feferonka",
    "feferonky",
    "fenykl",
    "file",
    "flora light",
    "flíčky",
    "forma",
    "formičky",
    "fusilli",
    "fíky",
    "ghí",
    "glutamát",
    "glutasol",
    "gnocchi",
    "gorgonzola",
    "gothaj",
    "granko",
    "grapefruit",
    "grenadina",
    "grepfruit",
    "grilovací koření",
    "griotka",
    "guacamole",
    "gulášová směs",
    "halušky",
    "hamburger",
    "hera",
    "hermelín",
    "hluchavka",
    "hlíva ústřičná",
    "houby",
    "houska",
    "hovězí maso",
    "hořčice",
    "hořčičné semínko",
    "hranolky",
    "hraška",
    "hrozny",
    "hrušky",
    "hrách",
    "hrášek",
    "hummus",
    "hřebíček",
    "hříbky",
    "ingredience:",
    "jablka",
    "jablko",
    "jahody",
    "jalapeňo",
    "jalovec",
    "jedlá soda",
    "jedlé květy",
    "jelito",
    "jikry",
    "jitrnice",
    "jogurt",
    "juice višňový",
    "jádra",
    "jáhly",
    "játra",
    "jíška",
    "kabanos",
    "kakao",
    "kaki",
    "kambucha",
    "kapary",
    "kapie",
    "kapr",
    "kapusta",
    "karamel",
    "kardamom",
    "kari",
    "kari koření",
    "karotka",
    "karé",
    "kaviár",
    "kaše",
    "kaštany",
    "kedlubna",
    "kedlubny",
    "kefír",
    "kerblík",
    "kernotto",
    "kečup",
    "kešu oříšky",
    "kinder pinguí",
    "kiwi",
    "klobása",
    "kmín",
    "knedlík",
    "knedlíčky",
    "knorr aromat",
    "kokos",
    "kokosové mléko",
    "kompot",
    "kopr",
    "kopřiva",
    "korbáčky",
    "koriandr",
    "korpus",
    "kotlety",
    "kozí rohy",
    "kořen galangalu",
    "krabí maso",
    "krabí tyčinky",
    "krenex",
    "krevety",
    "krkovice",
    "kroupy",
    "krupice",
    "krupky",
    "krutony",
    "králičí hlava",
    "králík",
    "krém",
    "krůtí maso",
    "kudrnka",
    "kukuřice",
    "kurkuma lžičky",
    "kuskus",
    "kuře",
    "kuřecí maso",
    "kuřecí prsa",
    "kvásek",
    "kvítek macešky",
    "květák",
    "kysaná smetana",
    "kysané zelí",
    "káva",
    "kýta",
    "křen",
    "kůra",
    "lanýže",
    "lasagne",
    "led",
    "ledová tříšť",
    "lentilky",
    "lečo",
    "lilek",
    "limetka",
    "linecká kolečka",
    "losos",
    "lupínky",
    "lusky",
    "lučina",
    "lékořice",
    "líbeček",
    "lískové ořechy",
    "maggi",
    "maizena",
    "majonéza",
    "majoránka",
    "makrela",
    "maliny",
    "mandarinky",
    "mandle",
    "mango",
    "marcipán",
    "marcipánová hmota",
    "margarín",
    "margotka",
    "marmeláda",
    "marmite",
    "marsmallow bonbony jojo",
    "mascarpone",
    "masox",
    "med",
    "meloun",
    "meruňky",
    "mikrotenový sáček",
    "mleté maso",
    "mléko",
    "mouka",
    "moučka",
    "mozzarella",
    "mořské plody",
    "mořský okoun",
    "mrkev",
    "muškátový květ",
    "muškátový oříšek",
    "mušle",
    "mák",
    "máslo",
    "máta",
    "müsli",
    "nachos",
    "nektarinka",
    "nektarinky",
    "nit",
    "niť",
    "nori",
    "nudle",
    "nugeta",
    "nugát",
    "nutela",
    "náplň",
    "nůž",
    "obilné klíčky",
    "ocet",
    "okurka",
    "okurky",
    "olej",
    "olivy",
    "omega malinko",
    "oplatky",
    "oregáno",
    "ostružiny",
    "ovesné vločky",
    "ovocný likér",
    "ořechy",
    "oříšky",
    "palačinky",
    "pancetta",
    "pangasius filety",
    "paprika",
    "papričky chipotle",
    "parmazán",
    "parmezan",
    "parmezán",
    "pasta",
    "pastinák",
    "patizony",
    "paštika",
    "pažitka",
    "pektin citrusový",
    "pelyněk",
    "penne rigate",
    "pepř",
    "pesto",
    "petržel",
    "petželka",
    "pečivo",
    "pečící papír",
    "physalis",
    "pide",
    "pinie",
    "pistácie",
    "pivo",
    "piškoty",
    "plátky krkovičky",
    "podravka",
    "pohanka",
    "polenta",
    "poleva",
    "poličan",
    "polníček",
    "polévkové koření",
    "pomazánka",
    "pomelo",
    "pomeranč",
    "posypka",
    "potravinářská folie",
    "potravinářské barvivo",
    "povidla",
    "preclíky",
    "prejt",
    "proso",
    "protlak",
    "prášek do pečiva",
    "pstruh",
    "puding",
    "pudink",
    "pyré",
    "pálenka",
    "párek",
    "párky",
    "párátka",
    "pórek",
    "quinoa",
    "rajčata",
    "rajče",
    "rama",
    "rebarbora",
    "rohlík",
    "romadůr",
    "rozinky",
    "rozmarýn",
    "rucola lístky",
    "rukola",
    "rum",
    "ryba",
    "rybičky ve šťávě",
    "ryby",
    "rybíz",
    "rýže",
    "salko",
    "salsa",
    "salám",
    "salát",
    "sardinky",
    "saturejka",
    "sedlina",
    "sekaná",
    "sekt",
    "sezam",
    "sirob",
    "sirup",
    "sklenice",
    "skopové maso",
    "skořice",
    "slanina",
    "slivovice",
    "smetana",
    "snítka kopru",
    "sněhové pusinky",
    "sodovka",
    "soja",
    "sojová omáčka",
    "sojové maso",
    "sojový granulát",
    "solamyl",
    "solčanka",
    "sorban",
    "srnčí hřbet",
    "sterilované kukuřičky",
    "strouhanka",
    "sumach",
    "sušenka",
    "sušenky",
    "sušené ovoce",
    "sádlo",
    "sýr",
    "sůl",
    "tabasco",
    "tatra",
    "teploměr",
    "tofu",
    "toping",
    "topinka",
    "tortilla chips",
    "treska",
    "tresť",
    "trubička sladká",
    "tuk",
    "tuzemák",
    "tuňák",
    "tvaroh",
    "tvarůžky",
    "tymián",
    "těsto",
    "těstoviny",
    "třešně",
    "ubrousek",
    "uzenina",
    "uzeniny",
    "uzené maso",
    "uzený jazyk vařený",
    "vaječná omeleta",
    "vaječný koňak",
    "vanilka",
    "vanilková esence",
    "vanilkové aroma",
    "vegeta",
    "vejce",
    "veka",
    "vepřové maso",
    "vinné listy",
    "višně",
    "vltavín",
    "voda",
    "vodka",
    "vojtěška miska",
    "vysočina",
    "václavky",
    "víno",
    "výhonky",
    "vývar",
    "věnečky",
    "wasabi",
    "whisky",
    "zasmážka",
    "zavařenina",
    "zelenina",
    "zelená nať",
    "zmrzlina",
    "zálivka",
    "zázvor",
    "čaj",
    "čekanka",
    "česnek",
    "čokoláda",
    "čočka",
    "čubrica",
    "řasa wakame",
    "ředkvička",
    "řeřicha",
    "řízek",
    "šafrán",
    "šalotka",
    "šalvěj",
    "šampaňské",
    "škeble",
    "škrob",
    "škvarky",
    "šlehačka",
    "špagety",
    "špejle",
    "špek",
    "špekáček",
    "špenát",
    "šunka",
    "švestky",
    "šťovík",
    "šťáva z kompotu",
    "žampiony",
    "želatina",
    "želatinový ztužovač",
    "želé",
    "želírovací prostředek gelfix 2:1, 3:1",
    "žemle",
    "žervé",
    "žloutek",
    "žloutky",
    "žmolenka",
]

def najdi_shodu(text):
    text_lower = text.lower()
    for ing in ocistene_ingredience:
        if ing in text_lower:
            return ing
    return None

with open(input_file, "r", encoding="utf-8") as infile, open(output_file, "w", encoding="utf-8") as outfile:
    for line in infile:
        match = re.search(r"IngredientName\s*=\s*'(.*?)'", line)
        if match:
            puvodni_ingredience = match.group(1)
            shoda = najdi_shodu(puvodni_ingredience)

            if shoda:
                nova_ingredience = f"IngredientName = '{shoda}'"
                line = re.sub(r"IngredientName\s*=\s*'(.*?)'", nova_ingredience, line)
                outfile.write(line)

print("Done")